import { Landmark, TrendingUp } from 'lucide-react';
import { observatorioData as d } from '../../data/observatorioData';
import { dispatchInspect } from '../DataInspector';
import { formatBudgetCurrency, formatPercent } from '../../utils/formatters';
import { Card } from '../ui/Card';
import { SectionHeader } from '../ui/SectionHeader';

export function BudgetSection() {
  const rows = [...d.budget.functions].sort((a,b) => b.amountBrl-a.amountBrl);
  return <section id="orcamento" className="mx-auto max-w-7xl px-4 py-14 sm:px-6" aria-labelledby="orcamento-title">
    <SectionHeader titleId="orcamento-title" eyebrow="Orçamento" title="LOA 2026: da cifra à narrativa" description="O total legal abre a leitura; abaixo, a distribuição por função e a alteração legislativa aparecem em camadas separadas." action={<div className="flex items-center gap-2 text-xs text-slate-500"><Landmark className="h-4 w-4" />{formatBudgetCurrency(d.budget.totalBrl)}</div>} />
    <div className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]">
      <button type="button" onClick={() => dispatchInspect({ label: 'LOA 2026', value: formatBudgetCurrency(d.budget.totalBrl), sourceId: d.budget.sourceId, status: 'current', note: 'Total legal da Lei Orçamentária Anual de 2026.' })} className="text-left"><Card><div className="text-xs font-bold uppercase tracking-[0.15em] text-slate-500">Orçamento total</div><div className="mt-3 text-4xl font-black text-white">{formatBudgetCurrency(d.budget.totalBrl)}</div><div className="mt-2 text-xs text-slate-500">Clique para abrir fonte e referência.</div><div className="mt-5 flex items-center gap-2 text-xs font-bold text-sky-300"><TrendingUp className="h-4 w-4" /> distribuição por função abaixo</div></Card></button>
      <Card><div className="text-xs font-bold uppercase tracking-[0.15em] text-slate-500">Alteração legislativa registrada</div>{d.budgetUpdates.map(update => <button key={update.law} type="button" onClick={() => dispatchInspect({ label: update.title, value: formatBudgetCurrency(update.amountBrl), sourceId: update.sourceId, referenceDate: update.date, status: 'alteração legislativa', note: update.description })} className="mt-3 w-full rounded-2xl border border-white/8 p-4 text-left"><div className="flex items-center justify-between gap-3"><strong className="text-white">{update.law}</strong><span className="text-xs font-bold text-sky-300">{formatBudgetCurrency(update.amountBrl)}</span></div><div className="mt-1 text-sm text-slate-400">{update.title}</div><p className="mt-2 text-xs leading-5 text-slate-500">{update.description}</p></button>)}</Card>
    </div>
    <Card className="mt-4"><div className="space-y-4">{rows.map(row => { const pct = (row.amountBrl / d.budget.totalBrl) * 100; return <button key={row.id} type="button" onClick={() => dispatchInspect({ label: 'LOA · ' + row.name, value: formatBudgetCurrency(row.amountBrl), sourceId: row.sourceId, status: 'current', note: 'Percentual derivado do total legal da LOA; funções não devem ser somadas como se fossem unidades independentes em todos os níveis.' })} className="grid w-full grid-cols-[1fr_auto] gap-3 text-left"><div><div className="flex items-center justify-between gap-4 text-sm"><span className="text-slate-300">{row.name}</span><strong className="text-white">{formatBudgetCurrency(row.amountBrl)}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-sky-300" style={{ width: Math.min(100,pct) + '%' }} /></div></div><div className="pt-0.5 text-right text-xs text-slate-500">{formatPercent(pct,1)}</div></button>})}</div><p className="mt-5 border-t border-white/8 pt-4 text-xs leading-5 text-slate-600">Leitura: o total legal, as funções e a alteração legislativa são camadas diferentes. O observatório não soma categorias que pertencem a níveis distintos.</p></Card>
  </section>;
}
