import { AlertTriangle, FileSearch, ShieldCheck } from 'lucide-react';
import { observatorioData as d } from '../../data/observatorioData';
import { Card } from '../ui/Card';
import { Badge } from '../ui/Badge';
import { SectionHeader } from '../ui/SectionHeader';

export function PoliticalRadar() {
  const poll = d.polls[0];
  return <section id="politica" className="mx-auto max-w-7xl px-4 py-14 sm:px-6" aria-labelledby="politica-title">
    <SectionHeader eyebrow="Eleições 2026" title="Pesquisa, contas e integridade em um mesmo radar" description="As informações políticas são apresentadas como registros e comparações documentais; o componente não produz recomendação eleitoral." />
    <div className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]">
      <Card><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[0.15em] text-slate-500">Pesquisa registrada</div><h3 className="mt-2 text-xl font-black text-white">{poll.pollster}</h3><p className="mt-1 text-xs text-slate-500">{poll.registrationNumber} · {poll.collectionDate} · {poll.interviews} entrevistas</p></div><Badge tone="warning">Ficha metodológica em auditoria</Badge></div><div className="mt-5 space-y-2">{poll.results.map(r => <div key={r.label} className="flex items-center gap-3"><div className="w-32 shrink-0 text-xs text-slate-400">{r.label}</div><div className="h-2 flex-1 rounded-full bg-white/5"><div className="h-full rounded-full bg-sky-300" style={{ width: `${Math.min(100, r.percentage * 2)}%` }} /></div><div className="w-14 text-right text-xs font-bold text-white">{r.percentage.toFixed(2).replace('.', ',')}%</div></div>)}</div><div className="mt-5 grid grid-cols-3 gap-3 text-xs"><div className="rounded-2xl border border-white/8 p-3"><strong className="block text-white">{poll.nonePct?.toFixed(2).replace('.', ',')}%</strong><span className="text-slate-500">Nenhum</span></div><div className="rounded-2xl border border-white/8 p-3"><strong className="block text-white">{poll.notSurePct?.toFixed(2).replace('.', ',')}%</strong><span className="text-slate-500">NS/NR</span></div><div className="rounded-2xl border border-white/8 p-3"><strong className="block text-white">±{poll.theoreticalMarginErrorPct?.toFixed(1).replace('.', ',')} pp</strong><span className="text-slate-500">teórico</span></div></div><p className="mt-4 text-xs leading-5 text-slate-500">Nenhum + NS/NR = 25,75% nesta pesquisa. Isso é um retrato daquele levantamento, não medida de “indecisão estrutural” da população.</p></Card>
      <Card><div className="text-xs font-bold uppercase tracking-[0.15em] text-slate-500">Checklist IA / 72h</div><div className="mt-4 space-y-3"><div className="flex gap-3 rounded-2xl border border-white/8 p-4"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-300" /><div><strong className="block text-white">Rotulagem</strong><p className="mt-1 text-xs leading-5 text-slate-400">Conteúdo sintético usado em propaganda deve identificar explicitamente a manipulação e a tecnologia utilizada.</p></div></div><div className="flex gap-3 rounded-2xl border border-white/8 p-4"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-300" /><div><strong className="block text-white">Janela especial</strong><p className="mt-1 text-xs leading-5 text-slate-400">Novos conteúdos sintéticos com imagem, voz ou manifestação de candidato ou pessoa pública têm vedação de publicação/republicação no intervalo definido pelo TSE.</p></div></div><div className="flex gap-3 rounded-2xl border border-white/8 p-4"><FileSearch className="mt-0.5 h-5 w-5 shrink-0 text-sky-300" /><div><strong className="block text-white">Prestação de contas</strong><p className="mt-1 text-xs leading-5 text-slate-400">A consulta oficial permite acompanhar bens, arrecadação, despesas e movimentação financeira. O snapshot parcial cobre fatos até 08/09/2026.</p></div></div></div></Card>
    </div>
  </section>;
}