// Barrel de ícones lucide-react com re-export explícito (tree-shaking real).
// Gerado por scripts/gen-icon-barrel.mjs — não editar manualmente.
export {
  Activity,
  TriangleAlert as AlertTriangle,
  ArrowDown,
  ArrowDownRight,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  ChartColumnBig as BarChart3,
  BookOpen,
  Braces,
  Brain,
  BusFront,
  CalendarClock,
  CalendarDays,
  Camera,
  Check,
  CircleCheckBig as CheckCircle2,
  CircleQuestionMark as CircleHelp,
  Clipboard,
  ClipboardCheck,
  Clock3,
  Coins,
  Command,
  Compass,
  Copy,
  Database,
  Download,
  Droplets,
  ExternalLink,
  FileCheckCorner as FileCheck2,
  FileQuestionMark as FileQuestion,
  FileSearch,
  FileText,
  FingerprintPattern,
  Gauge,
  GitPullRequest,
  HeartPulse,
  RotateCcwClock as History,
  House as Home,
  Image,
  Landmark,
  Languages,
  LayoutDashboard,
  Link2,
  Map,
  MapPin,
  Menu,
  MessageCircle,
  Minus,
  Moon,
  Radio,
  RefreshCw,
  RotateCcw,
  Route,
  Scale,
  Search,
  SearchCheck,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Sun,
  TrendingUp,
  TriangleAlert,
  UserRound,
  Users,
  UsersRound,
  Vote,
  Wallet,
  WalletCards,
  X,
  CircleX as XCircle,
} from 'lucide-react';
